version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8000"
    environment:
      - PYTHONPATH=/app
      - INDEXER_TYPE=suffix
      - FIT_EMBEDDING_MODEL=true
      - DATA_DIR=/app/data
      - ENABLE_PERSISTENCE=true
      - SNAPSHOT_INTERVAL=300
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
