[tool.pytest]
testpaths = ["tests"]
pythonpath = ["."]
asyncio_mode = "auto"
addopts = "--cov=windsurf_project --cov-report=term-missing --cov-report=html"
log_cli = true
log_cli_level = "INFO"
mark_expressions = "asyncio = 'asyncio'"
